# Generated by Django 3.0.7 on 2020-06-24 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0002_inventario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directorioipc',
            name='id',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='directorioipc',
            name='razon_social',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
