# Generated by Django 3.0.7 on 2020-06-21 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
        ('formatos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovMercadoCab',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('anio', models.CharField(blank=True, max_length=4, null=True)),
                ('mes', models.CharField(blank=True, max_length=2, null=True)),
                ('n_semana', models.CharField(blank=True, max_length=1, null=True)),
                ('n_dia', models.CharField(blank=True, max_length=1, null=True)),
                ('hora_ini', models.CharField(blank=True, max_length=10, null=True)),
                ('hora_fin', models.CharField(blank=True, max_length=10, null=True)),
                ('id_inv', models.CharField(blank=True, max_length=5, null=True)),
                ('id_ciudad', models.CharField(blank=True, max_length=5, null=True)),
                ('id_mercado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shared.DirectorioIPC')),
            ],
        ),
        migrations.CreateModel(
            name='MovMercadoDet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_producto', models.CharField(blank=True, max_length=5, null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('id_ce', models.CharField(blank=True, max_length=1, null=True)),
                ('id_cc', models.CharField(blank=True, max_length=1, null=True)),
                ('id_mov_mercado_cab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='formatos.MovMercadoCab')),
            ],
        ),
        migrations.DeleteModel(
            name='Mercado',
        ),
    ]
