# Generated by Django 3.0.7 on 2020-06-23 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formatos', '0002_auto_20200621_1609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movmercadodet',
            old_name='id_cc',
            new_name='cc',
        ),
        migrations.RenameField(
            model_name='movmercadodet',
            old_name='id_ce',
            new_name='ce',
        ),
    ]
