# Generated by Django 3.0.7 on 2020-06-23 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0002_inventario'),
        ('formatos', '0004_auto_20200622_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movmercadodet',
            name='id_mov_mercado_cab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='detalles', to='formatos.MovMercadoCab'),
        ),
        migrations.AlterField(
            model_name='movmercadodet',
            name='id_producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shared.Producto'),
        ),
    ]
