# Generated by Django 3.0.7 on 2020-06-27 04:00

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('formatos', '0007_auto_20200623_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movmercadocab',
            name='ciudad',
        ),
    ]
